"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from xml.etree.ElementInclude import include
from setuptools import setup

APP = ["gamemaster.pyw"]
DATA_FILES = ['gamemaster.pyw', 'header_alt.png', 'kofi.png','doc.png','discord.png','github.png']
OPTIONS = {'iconfile': '/Users/e/Documents/GitHub/GameMaster/icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    include=['PIL']
)
